const colors = {
  rice: '#FFE9A5',
  pear: '#A2B71E',
  appleGreen: '#A0C132',
  appleRed: '#E63420',
  orange: '#FF9015',
  sweePotato: '#A43E2A',
  melon: '#BFD276',
  mangoGreen: '#C4D61E',
  mangoYellow: '#FFB001',
  peach: '#FE6D6C',
  flower: '#FBA1A1',
  strawberry: '#E66963',
  riceRed: '#F6D2C6',
  coffee: '#71441B',
  millet: '#D08043',
  cron: '#D5E896',
}

interface Data{
  itemId:string,
  title:string,
  color?:string,
  image?:string,
  price?:string,
  maturity?:string,
  packageSize?:string,
  place?:string,
  describe?:string | undefined,
}

export const data:Data[] = [
  {
    itemId: '00',
    title: '富士苹果',
    color:colors.appleRed,
    image: '/assets/farm/Apple.jpg',
    price: '288',
    maturity: '预计成熟时间：11月',
    packageSize: '箱规：4斤/箱',
    place: '产地：辽宁朝阳',
  },
  {
    itemId: '01',
    title: '芒果',
    color:colors.mangoYellow,
    image: '/assets/farm/mango.jpg',
    price: '199',
    maturity: '预计成熟时间：6月',
    packageSize: '箱规：4斤/箱',
    place: '产地：辽宁朝阳',
  },
  {
    itemId: '03',
    title: '大米',
    color:colors.rice,
    image: '/assets/farm/rice.jpg',
    price: '288',
    maturity: '预计成熟时间：11月',
    packageSize: '箱规：4斤/箱',
    place: '产地：辽宁朝阳',
  },
  {
    itemId: '04',
    title: '西瓜',
    color:colors.melon,
    image: '/assets/farm/watermelon.jpg',
    price: '199',
    maturity: '预计成熟时间：6月',
    packageSize: '箱规：4斤/箱',
    place: '产地：辽宁朝阳',
  },
  {
    itemId: '05',
    title: '咖啡',
    color:colors.coffee,
    image: '/assets/farm/coffee.jpg',
    price: '288',
    maturity: '预计成熟时间：11月',
    packageSize: '箱规：4斤/箱',
    place: '产地：辽宁朝阳',
  },
  {
    itemId: '06',
    title: '咖啡之旅',
    color:colors.appleGreen,
    image: '/assets/farm/coffeeBlog.jpg',
    describe:'云南·普洱野鸭塘河谷咖啡庄园云南·普洱野鸭塘河谷咖啡庄园云南·普洱野鸭塘河谷咖啡庄园云南·普洱野鸭塘河谷咖啡庄园云南·普洱野鸭塘河谷咖啡庄园云南·普洱野鸭塘河谷咖啡庄园'
  },
]
